services:
  - type: web
    name: youtube-clone-backend
    env: node
    region: oregon
    plan: free
    rootDir: Backend
    buildCommand: npm ci --ignore-scripts && npm run build && npm prune --production
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_IGNORE_SCRIPTS
        value: true
