services:
  - type: web
    name: youtube-clone-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false && npm run build && npm prune --production
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production

databases:
  - name: youtube-clone-db
    databaseName: YoutubeClone
    user: postgres
    region: oregon
    plan: free
